#!/bin/bash


STORAGE="backups"

function list_dbs() {
	show_dbs=`psql -c '\copy (SELECT datname FROM pg_database WHERE datistemplate = false) To STDOUT WITH CSV' | grep -v postgres | xargs`

	names=( $show_dbs )

	select name in "${names[@]}"; do
    		if [ -n "$name" ]; then 
			break;
    		fi;
	done
}

function backup() {
	list_dbs;
	_now=$(date +"%m%d%Y%H%M%S");
	_file="$STORAGE/backup_$_now.sql";

	pg_dump -U postgres "$name" -f "$_file";
}

function restore() {
	echo "Select SQL file to restore";
	show_bkps=`ls $STORAGE | xargs`

        rnames=( $show_bkps )

        select rname in "${rnames[@]}"; do
                if [ -n "$rname" ]; then
                        break;
                fi;
        done

	echo "Select db to use";

        show_dbs=`psql -c '\copy (SELECT datname FROM pg_database WHERE datistemplate = false) To STDOUT WITH CSV' | grep -v postgres | xargs`

        names=( $show_dbs );

        select name in "${names[@]}"; do
                if [ -n "$name" ]; then
                        break;
                fi;
        done

	psql -d "$name" -f "$STORAGE/$rname";
	
}



#backup;
#restore;

select m in b r
do
  case "$m" in
        "b")
        backup;  
	break
          ;;
        "r")
	restore;
	  break
          ;;
	*) echo invalid option;;
  esac
done


echo "|$name|"
