#!/bin/bash

adb kill-server
sudo pkill -9 adb

rm /etc/udev/rules.d/99-android.rules

echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fce", ATTRS{idProduct}=="61aa", MODE="0666"' > /etc/udev/rules.d/99-android.rules
sudo chmod a+r /etc/udev/rules.d/99-android.rules

sudo restart udev

adb devices